# Temp fix
CFLAGS_msm_ispif.o += -Wno-maybe-uninitialized
# Temp fix
ccflags-y += -Idrivers/media/platform/msm/camera_v2
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/io
obj-$(CONFIG_MSM_CSID) += msm_ispif.o
